### ISSUE TITLE
test program is broken

### ISSUE THREAD

**Issue by stevengj** [JuliaInterop/pyjulia#8]
`python -m unittest test.test_core` (from the travis file) gives:
```
Traceback (most recent call last):
  File "/Users/stevenj/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/stevenj/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/stevenj/anaconda/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/Users/stevenj/anaconda/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/Users/stevenj/anaconda/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/Users/stevenj/anaconda/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/Users/stevenj/anaconda/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/stevenj/anaconda/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_core'
macstation004:pyjulia stevenj$ 
```
@jakebolewski, I don't really understand the Python module logic; can you fix?

**Comment by Keno** [comment]
As stated the solution is to run from the main directory rather than the test directory.
